// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import vue from 'eslint-plugin-vue';

export default tseslint.config(
  {
    ignores: [
      '**/dist',
      '**/dist-pages',
      '**/storybook-static',
      '**/node_modules',
      '**/coverage',
      '**/.astro',
      // Generated by apps/docs/scripts (registry + palette).
      '**/*.generated.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Node-run tooling scripts (build helpers, scaffolds) — allow Node globals.
    files: ['scripts/**/*.{js,mjs,cjs}', '**/scripts/**/*.{js,mjs,cjs}', '**/*.mjs'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly', URL: 'readonly' },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      // Allow intentionally-unused identifiers prefixed with `_` (e.g. the
      // required override-signature params on the Web Components base class).
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Vue composables share the `use*` naming convention, so React's hook
    // rules misfire outside the React package.
    files: ['packages/vue/**/*.{ts,tsx}', 'packages/web-components/**/*.ts'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/exhaustive-deps': 'off',
    },
  },
  // Lint the Vue SFCs too (vue-eslint-parser for templates, the TS parser for
  // <script setup lang="ts"> blocks).
  ...vue.configs['flat/recommended'].map((cfg) => ({ ...cfg, files: ['**/*.vue'] })),
  {
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
    rules: {
      // The <script setup lang="ts"> blocks are type-checked by vue-tsc, which
      // already flags undefined identifiers (same reasoning as ts-eslint).
      'no-undef': 'off',
      // The library renders class names only; props are typed via TS unions,
      // so prop-type/default rules add noise rather than safety here.
      'vue/require-default-prop': 'off',
      // ARIA passthrough props ('aria-label' on Toolbar, …) keep their
      // attribute spelling on purpose.
      'vue/prop-name-casing': 'off',
      // Single-word names like `Button` mirror the React source of truth.
      'vue/multi-word-component-names': 'off',
      // Formatting is prettier's job; don't fight it on template layout.
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/first-attribute-linebreak': 'off',
    },
  },
);
